### ISSUE TITLE
Question about warpping of right image

### ISSUE THREAD

**Issue by SwagJ** [prstrive/EPCDepth#4]
Hi @prstrive,

Thank you for your great work. I have one question regarding to the warpping process. Specifically about the variable 'stereo_T'. In this segment of  code: https://github.com/prstrive/EPCDepth/blob/84119c806741334b652749ee953e3eab60a3718c/dataset/kitti_dataset.py#L164 
Why multiply 0.1 instead of the baselines of the cameras, which is 0.54 for KITTI?

Thank you in advance.

Best,

**Comment by prstrive** [comment]
There will be a scale difference in unsupervised depth estimation, so it is OK to take 0.1 or 0.54. Here we inherit directly from [depth-hint](https://github.com/nianticlabs/depth-hints/blob/aa2ecf7bc88ef2edbd434fbf064ac024cec8e85d/datasets/mono_dataset.py#L213).

**Comment by SwagJ** [comment]
Hi @prstrive, 

Thank you for your swift reply. Just one extra question. Have you tried to run experiment with 0.54? If so, will this cause significant performance boost/downgrade? Thank you.

**Comment by prstrive** [comment]
Sorry, we didn't run the experiment with 0.54. But what I can share with you is that we will multiply a [baseline coefficient](https://github.com/prstrive/EPCDepth/blob/84119c806741334b652749ee953e3eab60a3718c/tools.py#L172) during testing. If you use 0.54 during training, change it to 1.0 [here](https://github.com/prstrive/EPCDepth/blob/84119c806741334b652749ee953e3eab60a3718c/tools.py#L172), and the effect should be similar.

**Comment by SwagJ** [comment]
Thank you for your reply. I ll try that myself. 

Best,
