### ISSUE TITLE
distortion between near cars and adjacent environment

### ISSUE THREAD

**Issue by darknightking** [prstrive/EPCDepth#7]
Thanks authors for the interesting idea in the paper.
In my test, the portion containing near car of the reconstructed point cloud is distorted, which means the disparity between near  obvious cars and environment background is not predicted distinctly.
I guess three reasons may cause this. First, the encoding part of the network is not deep enough, the semantic is not learned well, so the difference between the environment and the vehicles may not be well judged. Second, the disparity output decoder contains down-sampled part, so the disparity of the car and adjacent environment may belong to the same grid in the output feature map. Third, the photo-metric loss contain lots of surrounding parts of the image such as the sky, making the fine-grained loss is submerged.
Please tell me if you ever encountered this situation.

**Comment by darknightking** [comment]
In KITTI source image, inferenced by your trained model50, it looks like that:
![image](https://user-images.githubusercontent.com/31091180/146345087-9abfef40-4c79-4517-94cc-550e47451804.png)

**Comment by prstrive** [comment]
The sharpness of object boundaries has always been a  formidable challenge, and it is beyond the scope of this article. The three points you mentioned are reasonable, and we suggest you look at the related work on sharpening the border, e.g. [ranking loss](https://openaccess.thecvf.com/content_CVPR_2020/papers/Xian_Structure-Guided_Ranking_Loss_for_Single_Image_Depth_Prediction_CVPR_2020_paper.pdf) and [displacement fields](https://openaccess.thecvf.com/content_CVPR_2020/papers/Ramamonjisoa_Predicting_Sharp_and_Accurate_Occlusion_Boundaries_in_Monocular_Depth_Estimation_CVPR_2020_paper.pdf).

**Comment by darknightking** [comment]
> The sharpness of object boundaries has always been a formidable challenge, and it is beyond the scope of this article. The three points you mentioned are reasonable, and we suggest you look at the related work on sharpening the border, e.g. [ranking loss](https://openaccess.thecvf.com/content_CVPR_2020/papers/Xian_Structure-Guided_Ranking_Loss_for_Single_Image_Depth_Prediction_CVPR_2020_paper.pdf) and [displacement fields](https://openaccess.thecvf.com/content_CVPR_2020/papers/Ramamonjisoa_Predicting_Sharp_and_Accurate_Occlusion_Boundaries_in_Monocular_Depth_Estimation_CVPR_2020_paper.pdf).

Thanks for your suggestion !
